doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        dbname: '%env(MYSQL_APP_DATABASE)%'
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            UserModelNamespace:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/IAM/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\IAM\User\Domain'
                alias: App
            TokenModelNamespace:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/IAM/Token/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\IAM\Token\Domain'
                alias: App
