lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    #token_ttl:        3600
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        #service: core.infrastructure.jwt_token_encoder
        #service:  lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: RS256
